version: '3.9'

services:
  backend:
    build: ./backend
    container_name: aah-backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    depends_on:
      - mongo
      - qdrant
      - n8n

  mongo:
    image: mongo:6
    container_name: aah-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: aah-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  n8n:
    image: n8nio/n8n:latest
    container_name: aah-n8n
    restart: unless-stopped
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

  redis:
    image: redis:7
    container_name: aah-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mongo_data:
  qdrant_data:
  n8n_data:



